### ISSUE TITLE
Hash计算的结果跟 https://emn178.github.io/online-tools/keccak_256.html 不一致

### ISSUE THREAD

**Issue by QuantProcessing** [hunjixin/keccak_cu#4]
Challenge: `01183c934f2b0bfb2b2b7c0e3028b6b2bbd3445ccc8508d7b67dff9ede02f0b3`
startNonce: `0`
thread: `1`
block: `1`
threadPerThread: `1`

hash result为：`0b983c934f2b0b7b2b2b7c0e3028b6b2bbd3445ccc8508d7b67dff9ede02f0b3`
pack result为：`01183c934f2b0bfb2b2b7c0e3028b6b2bbd3445ccc8508d7b67dff9ede02f0b30000000000000000000000000000000000000000000000000000000000000000`

使用 [https://emn178.github.io/online-tools/keccak_256.html](url) 在线程序计算 pack result，结果为 `9f4927f33fd81594b478945ec9f96a5f37c6e50f34df79359bb1d9d89e0cb62e`

**Comment by hunjixin** [comment]
thread要是32的倍数， 这个算法原理是32个线程即一个wrap计算一个hash
